[package]
name = "tmux-tat"
version = "0.1.0"
authors = ["Donny Johnson <itchychips@itchyeyes.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.77"
os_pipe = "0.9.2"
